spring:
  datasource:
    username: ${USER_LOGIN}  
    password: ${USER_PASSWORD}    
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        default_schema: stocks
